<div class="md:hidden" x-data="{ open: false, servicesOpen: false }" x-effect="document.documentElement.classList.toggle('overflow-hidden', open)" @keydown.escape.window="open = false">
    <button type="button" @click="open = true" class="flex h-12 w-12 items-center justify-center rounded-xl border border-white/25 transition hover:border-clay hover:bg-white/10" aria-label="Open navigation" :aria-expanded="open"><svg width="23" height="23" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button>
    <div x-cloak x-show="open" x-transition.opacity.duration.300ms class="fixed inset-0 z-[110] bg-forest-deep/70 backdrop-blur-sm" @click="open = false" aria-hidden="true"></div>
    <aside x-cloak x-show="open" x-transition:enter="transition ease-out duration-300" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" x-transition:leave="transition ease-in duration-250" x-transition:leave-start="translate-x-0" x-transition:leave-end="translate-x-full" class="fixed inset-y-0 right-0 z-[120] flex h-dvh w-[min(92vw,25rem)] flex-col overflow-y-auto overscroll-contain bg-ivory text-forest shadow-2xl" role="dialog" aria-modal="true" aria-label="Mobile navigation">
        <div class="flex items-center justify-between border-b border-white/10 bg-forest px-6 py-5 text-white"><a href="{{ route('home') }}" @click="open = false"><img src="{{ asset('images/packers-nepal-logo.png') }}" width="800" height="267" alt="Packers Nepal" class="h-14 w-auto max-w-[220px] object-contain"></a><button type="button" @click="open = false" class="flex h-11 w-11 shrink-0 items-center justify-center rounded-full border border-white/20 transition hover:border-clay hover:text-clay" aria-label="Close navigation"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 6 12 12M18 6 6 18"/></svg></button></div>
        <div class="mx-6 mt-5 flex items-center justify-between gap-4 rounded-2xl border border-clay/15 bg-[#fff1e8] p-4"><div><p class="text-[.62rem] font-bold uppercase tracking-[.16em] text-forest/45">Planning your packing?</p><p class="mt-1 text-sm font-extrabold">A little help to get started.</p></div><a href="{{ route('quote.request') }}" @click="open = false" class="shrink-0 rounded-xl bg-forest px-4 py-3 text-xs font-extrabold text-white">Get a quote ↗</a></div>
        <nav class="flex-1 px-6 py-7" aria-label="Mobile main navigation"><p class="mb-4 px-2 text-xs font-extrabold uppercase tracking-[.2em] text-clay">Explore</p><div class="space-y-2">
            <a href="{{ route('home') }}" @click="open = false" class="flex items-center gap-4 rounded-xl bg-clay/10 p-3 font-extrabold text-clay"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-white"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m3 11 9-8 9 8M5 10v11h14V10M9 21v-7h6v7"/></svg></span><span>Home</span><span class="ml-auto">›</span></a>
            <a href="{{ route('page.show', 'about') }}" @click="open = false" class="flex items-center gap-4 rounded-xl p-3 font-extrabold transition hover:bg-sage"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-sage"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-6v-4m0-4h.01"/></svg></span><span>About Us</span><span class="ml-auto text-forest/35">›</span></a>
            <div><button type="button" @click="servicesOpen = ! servicesOpen" class="flex w-full items-center gap-4 rounded-xl p-3 text-left font-extrabold transition hover:bg-sage" :aria-expanded="servicesOpen" aria-controls="mobile-services-menu"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-sage"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m12 3 8 4.5v9L12 21l-8-4.5v-9L12 3ZM4 7.5l8 4.5 8-4.5M12 12v9"/></svg></span><span>Services</span><svg class="ml-auto transition" :class="servicesOpen && 'rotate-180'" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 9 6 6 6-6"/></svg></button><div id="mobile-services-menu" x-show="servicesOpen" x-collapse class="ml-[4.25rem] space-y-1 pb-2">@foreach($activeServices as $menuService)<a href="{{ route('services.show', $menuService) }}" @click="open = false" class="block rounded-lg px-3 py-2 text-sm text-forest/65 hover:bg-sage hover:text-forest">{{ $menuService->name }}</a>@endforeach</div></div>
            @foreach([['How It Works', route('page.show', 'how-it-works'), 'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-6v-5m0-3h.01'],['Contact', route('contact'), 'M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4ZM8 9h8M8 13h5']] as [$label, $url, $path])<a href="{{ $url }}" @click="open = false" class="flex items-center gap-4 rounded-xl p-3 font-extrabold transition hover:bg-sage"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-sage"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="{{ $path }}"/></svg></span><span>{{ $label }}</span><span class="ml-auto text-forest/35">›</span></a>@endforeach
        </div><div class="my-7 border-t border-forest/10"></div><p class="mb-4 px-2 text-xs font-extrabold uppercase tracking-[.2em] text-clay">Start here</p><a href="{{ route('quote.request') }}" @click="open = false" class="flex items-center gap-4 rounded-xl bg-sage p-3 font-extrabold"><span class="flex h-11 w-11 items-center justify-center rounded-xl bg-white"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 3h12v18H6zM9 8h6M9 12h6M9 16h3"/></svg></span><span>Request a quote</span><span class="ml-auto">›</span></a></nav>
        <div class="m-6 mt-0 rounded-2xl bg-forest p-5 text-white"><a href="tel:+9779801010000" class="flex items-center gap-4"><span class="flex h-12 w-12 shrink-0 items-center justify-center rounded-full bg-clay"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.4 19.4 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7 13 13 0 0 0 .7 2.8 2 2 0 0 1-.5 2.1L8.1 9.8a16 16 0 0 0 6 6l1.2-1.2a2 2 0 0 1 2.1-.5c.9.3 1.8.6 2.8.7a2 2 0 0 1 1.8 2.1Z"/></svg></span><span><span class="block text-xs text-white/60">Need a hand? Call our team</span><strong class="mt-1 block text-lg">9801010000</strong></span></a></div>
    </aside>
</div>
