<div>
    <section class="relative overflow-hidden bg-forest text-white"><div class="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_1px_1px,white_1px,transparent_0)] [background-size:28px_28px]"></div><div class="shell relative grid min-h-[430px] gap-10 py-16 lg:grid-cols-[1fr_.75fr] lg:items-center"><div><p class="eyebrow !text-white/65">Contact Packers Nepal</p><h1 class="display mt-6 text-5xl leading-tight sm:text-6xl">Let’s talk about what needs <span class="text-clay">care.</span></h1><p class="mt-6 max-w-2xl text-lg leading-8 text-white/70">Ask a question about our packing services, service area, materials, or process. For pricing, you can also send a detailed packing quote request.</p></div><div class="hidden overflow-hidden rounded-2xl lg:block"><img src="{{ asset('images/service-household.jpg') }}" alt="Packers Nepal household packing specialist" class="aspect-[4/3] w-full object-cover"></div></div></section>

    <section class="shell grid gap-10 py-20 lg:grid-cols-[.72fr_1.28fr] lg:items-start">
        <aside class="space-y-5 lg:sticky lg:top-32"><div><p class="eyebrow">We’re here to help</p><h2 class="section-heading">Speak with a packing specialist.</h2><p class="mt-5 leading-7 text-forest/65">Send your message securely or contact our office directly.</p></div><div class="surface divide-y divide-forest/10 overflow-hidden"><div class="p-6"><p class="text-xs font-bold uppercase tracking-[.18em] text-clay">Address</p><p class="mt-3 font-extrabold">{{ $siteSettings?->address ?? 'New Road, Kathmandu' }}</p></div><div class="p-6"><p class="text-xs font-bold uppercase tracking-[.18em] text-clay">Phone</p><a href="tel:{{ preg_replace('/[^0-9+]/', '', $siteSettings?->phone ?? '9801010000') }}" class="mt-3 block font-extrabold transition hover:text-clay">{{ $siteSettings?->phone ?? '9801010000' }}</a></div><div class="p-6"><p class="text-xs font-bold uppercase tracking-[.18em] text-clay">Email</p><a href="mailto:{{ $siteSettings?->email ?? 'info@packersnepal.com' }}" class="mt-3 block break-all font-extrabold transition hover:text-clay">{{ $siteSettings?->email ?? 'info@packersnepal.com' }}</a></div></div><div class="surface p-6"><p class="text-xs font-bold uppercase tracking-[.18em] text-clay">Service area</p><p class="mt-3 font-extrabold">{{ $siteSettings?->service_area ?? 'Kathmandu Valley and agreed locations across Nepal' }}</p></div><div class="rounded-2xl bg-sage p-6"><p class="font-extrabold">Need a price estimate?</p><p class="mt-2 text-sm leading-6 text-forest/65">Use the detailed quote form so we receive the location, service, and preferred date.</p><a href="{{ route('quote.request') }}" class="text-link mt-5">Request a packing quote <span aria-hidden="true">↗</span></a></div></aside>

        <div class="surface bg-white p-6 sm:p-9 lg:p-11">
            @if($reference)
                <div role="status" class="py-10"><span class="flex h-16 w-16 items-center justify-center rounded-full bg-clay text-2xl text-white" aria-hidden="true">✓</span><h2 class="display mt-6 text-4xl">Thank you for contacting us.</h2><p class="mt-4 leading-7 text-forest/70">Your message has been received. Keep this reference for your records:</p><p class="mt-4 break-all rounded-xl bg-mist p-4 font-mono text-sm">{{ $reference }}</p><a href="{{ route('home') }}" class="button mt-8">Return home</a></div>
            @else
                <form wire:submit="submit" class="space-y-6">
                    <div class="border-b border-forest/10 pb-6"><p class="text-xs font-bold uppercase tracking-[.18em] text-clay">Send a message</p><h2 class="display mt-3 text-3xl">How can we help?</h2><p class="mt-2 text-sm text-forest/60">All fields are required.</p></div>
                    <div class="grid gap-5 sm:grid-cols-2"><div><label for="contact-name" class="text-sm font-bold">Your name</label><input id="contact-name" wire:model="name" type="text" autocomplete="name" required class="field">@error('name')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div><div><label for="contact-email" class="text-sm font-bold">Email address</label><input id="contact-email" wire:model="email" type="email" autocomplete="email" required class="field">@error('email')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div></div>
                    <div><label for="contact-phone" class="text-sm font-bold">Phone number</label><input id="contact-phone" wire:model="phone" type="tel" autocomplete="tel" required class="field">@error('phone')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
                    <div><label for="contact-subject" class="text-sm font-bold">Subject</label><input id="contact-subject" wire:model="subject" type="text" required maxlength="180" class="field" placeholder="How can we help?">@error('subject')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
                    <div><label for="contact-message" class="text-sm font-bold">Message</label><textarea id="contact-message" wire:model="message" rows="6" required minlength="10" maxlength="5000" class="field" placeholder="Tell us your question or packing requirement..."></textarea>@error('message')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
                    <div class="hidden" aria-hidden="true"><label for="contact-website">Website</label><input id="contact-website" wire:model="website" tabindex="-1" autocomplete="off"></div>
                    <div><label class="flex items-start gap-3 text-sm leading-6"><input wire:model="consent" type="checkbox" required class="mt-1 h-4 w-4 accent-clay"><span>I agree that Packers Nepal may store these details and contact me about this message.</span></label>@error('consent')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
                    <button type="submit" class="button w-full" wire:loading.attr="disabled"><span wire:loading.remove wire:target="submit">Send message <span aria-hidden="true">↗</span></span><span wire:loading wire:target="submit">Sending…</span></button>
                </form>
            @endif
        </div>
    </section>
</div>
