<div class="shell grid gap-12 py-14 lg:grid-cols-[0.72fr_1.28fr] lg:items-start lg:py-20">
    <aside class="lg:sticky lg:top-36"><p class="eyebrow">A good place to start</p><h1 class="display mt-6 text-5xl leading-[1.05] sm:text-6xl">Let's take care<br>of the packing.</h1><p class="mt-6 max-w-md text-lg leading-8 text-forest/65">Tell us about your space and the things you need packed. We will review your request before agreeing on a price and date.</p><div class="mt-10 max-w-md rounded-2xl border border-forest/10 bg-sage p-6"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-forest text-white" aria-hidden="true">✓</span><h2 class="font-bold">Packing, clearly defined</h2></div><p class="mt-4 text-sm leading-6 text-forest/70">We pack at your location and prepare goods for handover. Transportation is arranged separately.</p><p class="mt-3 text-sm leading-6 text-forest/70">Your preferred date remains a request until our team confirms availability.</p></div><div class="mt-8 grid max-w-md grid-cols-3 gap-2 text-center text-[0.65rem] font-bold uppercase tracking-[.12em] text-forest/55"><span class="rounded-xl border border-forest/10 px-2 py-3">Request</span><span class="rounded-xl border border-forest/10 px-2 py-3">Review</span><span class="rounded-xl border border-forest/10 px-2 py-3">Confirm</span></div></aside>
    <section class="surface bg-white p-6 sm:p-9 lg:p-11" aria-label="Packing quote form">
        @if($reference)
            <div role="status" class="py-12"><span class="flex h-16 w-16 items-center justify-center rounded-full bg-leaf text-2xl" aria-hidden="true">✓</span><h2 class="display mt-6 text-4xl">Your request is with us.</h2><p class="mt-4 leading-7 text-forest/70">Keep this reference for your records:</p><p class="mt-3 break-all rounded-xl border border-forest/10 bg-ivory p-4 font-mono text-sm">{{ $reference }}</p><p class="mt-5 text-sm leading-6 text-forest/65">Our team can now review your packing needs. This acknowledgment does not confirm a price or booking.</p><a href="{{ route('home') }}" class="button mt-8">Back to home</a></div>
        @else
            <form wire:submit="submit" class="space-y-6">
                <div class="border-b border-forest/10 pb-6"><p class="text-xs font-bold uppercase tracking-[.18em] text-clay">Your packing details</p><h2 class="display mt-3 text-3xl">Tell us what needs care.</h2><p class="mt-2 text-sm text-forest/60">All fields are required except your preferred date.</p></div>
                <div class="grid gap-5 sm:grid-cols-2">
                    @foreach(['name' => 'Your name', 'email' => 'Email address', 'phone' => 'Phone number'] as $field => $label)
                        <div class="{{ $field === 'name' ? 'sm:col-span-2' : '' }}"><label for="{{ $field }}" class="text-sm font-bold">{{ $label }}</label><input id="{{ $field }}" wire:model="{{ $field }}" type="{{ $field === 'email' ? 'email' : ($field === 'phone' ? 'tel' : 'text') }}" autocomplete="{{ $field === 'phone' ? 'tel' : $field }}" required class="field" aria-describedby="{{ $field }}-error" @error($field) aria-invalid="true" @enderror><p id="{{ $field }}-error" class="mt-1 text-sm text-red-700">@error($field) {{ $message }} @enderror</p></div>
                    @endforeach
                </div>
                <div><label for="service_id" class="text-sm font-semibold">What needs packing?</label><select id="service_id" wire:model="service_id" required class="field" aria-describedby="service-error"><option value="">Select a service</option>@foreach($services as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select><p id="service-error" class="mt-1 text-sm text-red-700">@error('service_id') {{ $message }} @enderror</p></div>
                <div><label for="address" class="text-sm font-semibold">Packing location</label><textarea id="address" wire:model="address" rows="2" required class="field" placeholder="Area, city, and address" aria-describedby="address-error"></textarea><p id="address-error" class="mt-1 text-sm text-red-700">@error('address') {{ $message }} @enderror</p></div>
                <div><label for="preferred_date" class="text-sm font-semibold">Preferred date <span class="font-normal text-forest/60">(optional)</span></label><input id="preferred_date" wire:model="preferred_date" type="date" min="{{ now('Asia/Kathmandu')->toDateString() }}" class="field" aria-describedby="date-error"><p id="date-error" class="mt-1 text-sm text-red-700">@error('preferred_date') {{ $message }} @enderror</p></div>
                <div><label for="details" class="text-sm font-semibold">Tell us a little more</label><textarea id="details" wire:model="details" rows="4" required minlength="10" maxlength="5000" class="field" placeholder="Approximate rooms or items, anything fragile, and any access requirements..." aria-describedby="details-error"></textarea><p id="details-error" class="mt-1 text-sm text-red-700">@error('details') {{ $message }} @enderror</p></div>
                <div class="hidden" aria-hidden="true"><label for="website">Website</label><input id="website" wire:model="website" tabindex="-1" autocomplete="off"></div>
                <div><label class="flex items-start gap-3 text-sm leading-6"><input wire:model="consent" type="checkbox" required class="mt-1 h-4 w-4 accent-forest"><span>I agree that Packers Nepal may store these details and contact me about this packing request.</span></label>@error('consent')<p class="mt-1 text-sm text-red-700">{{ $message }}</p>@enderror</div>
                <button type="submit" class="button w-full" wire:loading.attr="disabled"><span wire:loading.remove wire:target="submit">Send my packing request <span aria-hidden="true">↗</span></span><span wire:loading wire:target="submit">Sending your request…</span></button>
                <p class="text-center text-xs leading-5 text-forest/45">Submitting a request does not confirm a price or reserve a date.</p>
            </form>
        @endif
    </section>
</div>
