<section class="relative overflow-hidden bg-forest text-white">
    <div class="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_1px_1px,white_1px,transparent_0)] [background-size:28px_28px]"></div>
    <div class="shell relative grid min-h-[520px] gap-12 py-20 lg:grid-cols-[1fr_.8fr] lg:items-center">
        <div><p class="eyebrow !text-white/65">Our packing process</p><h1 class="display mt-6 max-w-3xl text-5xl leading-[1.02] sm:text-6xl lg:text-7xl">From your request to a <span class="text-clay">careful handover.</span></h1><p class="mt-7 max-w-2xl text-lg leading-8 text-white/70">A clear, practical process for protecting and organizing your belongings before they are collected by the transporter you choose.</p><a href="{{ route('quote.request') }}" class="button mt-9">Start with a quote <span aria-hidden="true">↗</span></a></div>
        <div class="relative hidden lg:block"><img src="{{ asset('images/service-office.jpg') }}" alt="Packers Nepal team carefully packing office equipment" class="aspect-[4/3] w-full rounded-2xl object-cover shadow-2xl"><div class="absolute -bottom-5 -left-5 rounded-xl bg-white p-5 text-forest shadow-xl"><strong class="display text-3xl text-clay">4 steps</strong><span class="mt-1 block text-xs font-bold uppercase tracking-wider text-forest/55">Simple and transparent</span></div></div>
    </div>
</section>

<section class="shell py-20 lg:py-28">
    <div class="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div class="lg:sticky lg:top-32"><p class="eyebrow">How it works</p><h2 class="section-heading">A smooth path from details to <span class="text-clay">packed.</span></h2><p class="mt-6 max-w-md leading-7 text-forest/65">You stay informed at each stage. We confirm scope and availability before work begins, then prepare everything for your chosen transport arrangement.</p><div class="relative mt-9 max-w-xl"><div class="overflow-hidden rounded-2xl"><img src="{{ asset('images/service-household.jpg') }}" alt="Packers Nepal specialist preparing a household item" class="aspect-[4/3] w-full object-cover" loading="lazy"></div><div class="absolute -bottom-5 left-5 right-5 flex items-center gap-4 rounded-xl bg-forest p-5 text-white shadow-xl"><span class="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-clay text-xl">✓</span><div><strong class="block text-sm font-extrabold">Packing service only</strong><span class="mt-1 block text-xs leading-5 text-white/60">Your chosen provider manages transportation.</span></div></div></div></div>
        <ol class="relative space-y-5 before:absolute before:bottom-12 before:left-7 before:top-12 before:w-px before:bg-clay/30">@foreach([['Share your packing needs','Tell us the location, preferred date, rooms or items involved, and anything requiring special care.'],['Review scope and quotation','Our team checks your request and clarifies materials, access, timing, and price. Your date is confirmed only after availability is checked.'],['We protect, pack, and label','Packing specialists work at the agreed location using suitable wrapping and a clear labeling system.'],['Check and hand over','You or your nominated contact reviews the finished work before the goods are released to your chosen transporter.']] as $step)<li class="surface relative flex gap-5 p-6 sm:gap-7 sm:p-8"><span class="relative z-10 flex h-14 w-14 shrink-0 items-center justify-center rounded-full bg-clay text-sm font-extrabold text-white">{{ sprintf('%02d', $loop->iteration) }}</span><div><h3 class="display text-2xl">{{ $step[0] }}</h3><p class="mt-3 leading-7 text-forest/65">{{ $step[1] }}</p></div></li>@endforeach</ol>
    </div>
</section>

<section class="bg-mist py-20"><div class="shell"><div class="grid gap-12 lg:grid-cols-2 lg:items-center"><div class="overflow-hidden rounded-2xl"><img src="{{ asset('images/service-fragile.jpg') }}" alt="Fragile glassware being wrapped by a Packers Nepal specialist" class="aspect-[4/3] w-full object-cover" loading="lazy"></div><div><p class="eyebrow">Before you request</p><h2 class="section-heading">A few details help us plan <span class="text-clay">properly.</span></h2><div class="mt-8 grid gap-4 sm:grid-cols-2">@foreach(['Packing location and access','Rooms or types of items','Fragile or high-care belongings','Preferred packing date','Approximate quantity','Your handover contact'] as $item)<div class="flex items-start gap-3 rounded-xl bg-white p-4"><span class="mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full bg-clay text-xs font-bold text-white">✓</span><span class="text-sm font-bold leading-6">{{ $item }}</span></div>@endforeach</div></div></div></div></section>

<section class="shell py-20 lg:py-28"><div class="grid gap-5 lg:grid-cols-3"><article class="rounded-2xl bg-forest p-8 text-white lg:col-span-2"><p class="eyebrow !text-white/65">What we manage</p><h2 class="display mt-6 text-4xl">Protection, organization, and clear labeling.</h2><p class="mt-5 max-w-2xl leading-8 text-white/70">Our agreed scope may cover cartons, protective wrapping, fragile-item preparation, room or category labels, and an organized final check. The exact materials and work are confirmed in your quotation.</p></article><article class="rounded-2xl bg-clay p-8 text-white"><p class="text-xs font-bold uppercase tracking-[.2em] text-white/70">What you arrange</p><h2 class="display mt-6 text-3xl">Transportation after packing.</h2><p class="mt-5 leading-7 text-white/80">You choose and coordinate the vehicle, transporter, collection time, destination, and transport insurance.</p></article></div></section>

<section class="shell pb-24"><div class="grid overflow-hidden rounded-2xl border border-forest/10 bg-white shadow-[0_28px_80px_-45px_rgba(8,47,53,.45)] lg:grid-cols-[1fr_.85fr]"><div class="p-8 sm:p-12"><p class="eyebrow">Published guidance</p><h2 class="display mt-6 text-3xl">The process in our current service terms.</h2><div class="mt-6 whitespace-pre-line leading-8 text-forest/65">{{ $page->published_content }}</div></div><div class="flex flex-col justify-center bg-sage p-8 sm:p-12"><p class="text-sm font-bold uppercase tracking-[.18em] text-clay">Ready to begin?</p><h2 class="display mt-5 text-4xl">Tell us what needs packing.</h2><p class="mt-5 leading-7 text-forest/65">Send the details and our team will review the work before confirming a price or date.</p><a href="{{ route('quote.request') }}" class="button mt-8 w-fit">Request a packing quote <span aria-hidden="true">↗</span></a></div></div></section>
